# Generated by Django 5.0.1 on 2024-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date and time"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date and time"
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="carousel/")),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Carousel",
                "verbose_name_plural": "Carousels",
                "db_table": "carousel",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date and time"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date and time"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="success_stories/")),
                ("visa_type", models.CharField(max_length=100)),
                ("visa_status", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Success Story",
                "verbose_name_plural": "Success Stories",
                "db_table": "success_story",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date and time"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date and time"
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="testimonials/")),
                ("description", models.TextField()),
                (
                    "rate",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "db_table": "testimonial",
                "ordering": ("order",),
            },
        ),
    ]
