# Generated by Django 5.0.1 on 2024-02-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="image",
            field=models.ImageField(null=True, upload_to="banner/"),
        ),
    ]
