# Generated by Django 5.0.1 on 2024-01-23 14:37

import backend.report.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date and time"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification date and time"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("passed_year", models.CharField(max_length=50)),
                ("gpa_percentage", models.CharField(max_length=50)),
                ("faculty", models.CharField(max_length=100)),
                ("desired_country", models.CharField(max_length=100)),
                ("desired_course", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudyAbroad",
            fields=[
                (
                    "formmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="report.formmixin",
                    ),
                ),
                (
                    "language_profiency",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[backend.report.validators.LanguageProfValidator],
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Abroad Request",
                "verbose_name_plural": "Study Abroad Requests",
                "db_table": "study_abroad",
                "ordering": ["created"],
            },
            bases=("report.formmixin",),
        ),
        migrations.CreateModel(
            name="TestPrepration",
            fields=[
                (
                    "formmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="report.formmixin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Prepration Request",
                "verbose_name_plural": "Test Prepration Requests",
                "db_table": "test_prepration",
                "ordering": ["created"],
            },
            bases=("report.formmixin",),
        ),
    ]
